
# services:
#   xerostomia_backend_api:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: xerostomia_backend_api
#     ports:
#       - "5000:5000"
#     env_file:
#       - .env
#     environment:
#       - DATABASE_URL=postgres://postgresX:1234@postgres-xerostomia-db:5432/xerostomia_db?sslmode=disable
#       - NEXTCLOUD_URL=http://nextcloud:80/remote.php/dav/files/admin
#     networks:
#       - xerostomia
#   xerostomia_db:
#     image: postgres:13
#     container_name: postgres-xerostomia-db
#     ports:
#       - "5434:5432"
#     environment:
#       POSTGRES_USER: postgresX
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: xero_db
#     networks:
#       - xerostomia

# networks:
#   xerostomia:



services:
  xerostomia_db:
    image: postgres:13
    container_name: postgres-xerostomia-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgresX
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: xero_db
    networks:
      - xerostomia

networks:
  xerostomia: